'use client';
import {useEffect,useState} from 'react';
import MetricCharts from './MetricCharts';
const names={instagram:'Instagram',tiktok:'TikTok'};
const statuses={missing:'Do przygotowania',mirror:'Wspólna rolka z Instagramem',approved:'Gotowy',ready:'Gotowy',draft:'Do akceptacji',verified:'Opublikowany',published:'Opublikowany',regenerating:'Generowanie', 'replacement-failed':'Błąd generowania',submitted:'Wysłany do Buffer',pending:'Do sprawdzenia',done:'Wykonane ręcznie',dismissed:'Pominięte'};
const num=n=>Number.isFinite(n)?n.toLocaleString('pl-PL',{maximumFractionDigits:1}):'—';
function EngagementCard({item,busy,save}){
 const [draft,setDraft]=useState(item.draft),[outcome,setOutcome]=useState(item.outcome),[copied,setCopied]=useState(false);
 return <article className="growth-card"><div className="meta"><span>{names[item.platform]}</span><span>{statuses[item.status]||item.status}</span></div><a href={item.source_url} target="_blank" rel="noreferrer">Sprawdź oryginalną publikację ↗</a><p>{item.reason}</p><details><summary>Kontekst źródłowy</summary><p className="caption">{item.source_text}</p></details>
 {item.draft?<><label>Propozycja komentarza<textarea maxLength={450} rows={4} value={draft} onChange={e=>setDraft(e.target.value)}/></label><label>Rezultat / notatka<textarea maxLength={1000} rows={2} value={outcome} onChange={e=>setOutcome(e.target.value)} placeholder="Np. otrzymaliśmy odpowiedź; bez przypisywania wzrostu zasięgu komentarzowi"/></label><div className="actions">
 {item.status==='pending'&&<button disabled={busy||!draft.trim()} onClick={()=>save({action:'engagement-update',id:item.id,status:'approved',draft,outcome})}>Zatwierdź tekst</button>}
 {['approved','done'].includes(item.status)&&<button onClick={async()=>{try{await navigator.clipboard.writeText(draft);setCopied(true);}catch{setCopied(false);}}}>{copied?'Skopiowano':'Kopiuj komentarz'}</button>}
 {item.status==='approved'&&<button disabled={busy} onClick={()=>save({action:'engagement-update',id:item.id,status:'done',draft,outcome})}>Potwierdzam ręczne dodanie</button>}
 {item.status==='done'&&<button disabled={busy} onClick={()=>save({action:'engagement-update',id:item.id,status:'done',draft,outcome})}>Zapisz rezultat</button>}
 {['pending','approved'].includes(item.status)&&<button disabled={busy} onClick={()=>save({action:'engagement-update',id:item.id,status:'dismissed',draft,outcome})}>Pomiń</button>}</div></>:<p>{item.status==='dismissed'?'Brak wystarczającego kontekstu do komentarza.':'Generator przygotuje propozycję w kolejnym cyklu.'}</p>}</article>;
}
export default function GrowthPanel({platform,data,busy,act}){
 const [growth,setGrowth]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState('plan'),[url,setUrl]=useState(''),[source,setSource]=useState(''),[history,setHistory]=useState(false);
 async function load(){try{const r=await fetch('/studio-social/api/growth',{cache:'no-store'});if(!r.ok)throw Error('Nie udało się pobrać planu wzrostu.');setGrowth(await r.json());setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{const initial=setTimeout(load,0),timer=setInterval(load,30000);return()=>{clearTimeout(initial);clearInterval(timer);};},[]);
 async function save(body){if(await act(body)){await load();return true;}return false;}
 if(!growth)return <p role="status">{error||'Ładowanie planu wzrostu…'}</p>;
 const summary=growth.summaries[platform],slots=growth.slots.filter(s=>s.platform===platform),report=growth.reports[0],experiments=(report?.data.experiments||[]).filter(x=>x.platform===platform);
 const items=growth.engagement.filter(x=>x.platform===platform&&(history||['pending','approved'].includes(x.status)));
 return <section className="growth-panel"><p className="eyebrow">{names[platform]} / PLAN WZROSTU</p><h2>Treść → publikacja → wynik → kolejny test</h2><p>Aktualny harmonogram i zasady studia. Nowe eksperymenty rozszerzają istniejący generator; nie zmieniają zatwierdzonych materiałów.</p>{error&&<p role="alert" className="error">{error}</p>}
 <nav aria-label="Plan wzrostu">{[['plan','Plan i kolejka'],['results','Wyniki i eksperymenty'],['engagement','Posty branżowe i komentarze']].map(([id,label])=><button key={id} aria-pressed={tab===id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==='plan'&&<><section className="stats"><article><small>Publikowanie</small><strong>{growth.paused?'Wstrzymane':'Aktywne'}</strong></article><article><small>Rolki</small><strong>{growth.reelsEnabled?'Aktywne':'Wstrzymane'}</strong></article><article><small>Zaplanowane terminy</small><strong>{slots.length}</strong></article></section>
 <p>Terminy poniżej pochodzą z modułu harmonogramu używanego przez worker. „Do przygotowania” oznacza brak materiału, a nie gotową publikację. Posty mają krótszą kolejkę roboczą niż rolki.</p>
 <div className="metrics-table" role="region" aria-label="Aktualny plan publikacji" tabIndex={0}><table><thead><tr><th>Warszawa</th><th>Format</th><th>Temat</th><th>Status</th></tr></thead><tbody>{slots.map(s=><tr key={s.day+s.format}><td>{s.day} · {String(s.hour).padStart(2,'0')}:00</td><td>{s.format==='reel'?'Rolka':platform==='tiktok'?'Karuzela':'Post'}</td><td>{s.topic||s.kind}</td><td>{statuses[s.status]||s.status}</td></tr>)}</tbody></table></div>
 <div className="growth-columns"><article className="growth-card"><h3>Codziennie</h3><p>Automatyczna publikacja, deduplikacja tekstów i obrazów oraz uzupełnianie kolejki według dotychczasowych zasad. Do 5 propozycji komentarzy po wyszukaniu publicznych źródeł.</p><p>Twoja część: sprawdzenie kontekstu, odpowiedzi i komentarze — około 10–15 minut. To sugerowany czas pracy.</p></article><article className="growth-card"><h3>Co tydzień / co 2 tygodnie</h3><p>Raport wyników zapisuje się co tydzień. Otwarcia nowych treści rotują między obserwacją, pytaniem i porównaniem. Co 2 tygodnie generator może zwiększyć udział skuteczniejszego otwarcia, jeśli próba jest wystarczająca.</p></article><article className="growth-card"><h3>Dystrybucja i reklama</h3><p>Udostępnij wybrane publikacje w Stories z konkretnym kontekstem. Raz w miesiącu przejrzyj formaty i kandydatów do współpracy. Promocja płatna wymaga osobnego budżetu i wyboru materiału po wynikach organicznych.</p></article></div>
 <details className="growth-card"><summary>Wspólne zasady używane przez generator</summary><p>{growth.brand}</p><p>{growth.writingRules}</p></details></>}
 {tab==='results'&&<><section className="stats"><article><small>Publikacje / ostatnie 30 dni</small><strong>{summary.count}</strong></article><article><small>Z odczytem wyświetleń</small><strong>{summary.measured}</strong></article><article><small>Mediana wyświetleń</small><strong>{num(summary.medianViews)}</strong></article></section><p>{summary.note}</p><MetricCharts key={platform} rows={summary.ranked} samples={data.metricSamples}/>
 <div className="metrics-table" role="region" aria-label="Porównanie treści" tabIndex={0}><table><thead><tr><th>Publikacja</th><th>Wyświetlenia</th><th>Udostępnienia / 1000</th><th>Komentarze / 1000</th><th>Śr. oglądanie (s)</th><th>Wizyty profilu</th></tr></thead><tbody>{summary.ranked.map(p=><tr key={p.media_id}><th><a href={p.permalink} target="_blank" rel="noreferrer">{p.topic}</a><small>{p.day} · {p.format==='reel'?'Rolka':'Post'}</small></th><td>{num(p.metrics?.views)}</td><td>{num(p.sharesPer1000)}</td><td>{num(p.commentsPer1000)}</td><td>{num(p.metrics?.averageWatchSeconds)}</td><td>{num(p.metrics?.profileVisits)}</td></tr>)}</tbody></table></div>
 <article className="growth-card"><h3>Testy otwarć</h3><p>Odczyt 48–72 godziny po publikacji. Minimum {growth.policy.minimumExamples} materiałów z co najmniej {growth.policy.minimumViews} wyświetleniami dla każdego wariantu, osobno dla platformy i formatu. Kryterium: mediana udostępnień na 1000 wyświetleń. To wskazówka redakcyjna, nie dowód przyczynowy.</p>{!report?<p>Pierwszy raport czeka na cykl workera.</p>:<><p>Ostatni przegląd: {new Date(report.created_at).toLocaleString('pl-PL')}</p><ul>{experiments.map(e=><li key={e.format+e.hook}>{e.format==='reel'?'Rolki':'Posty'} · {growth.policy.hooks.find(h=>h.id===e.hook)?.label}: {e.n} próbek · {e.ready?num(e.medianSharesPer1000)+' udostępnień / 1000':'Za mało danych'}</li>)}</ul></>}</article>
 <p>Czas oglądania i wizyty profilu pokazujemy tylko tam, gdzie API zwraca odczyt. „—” oznacza brak danych. API nie dostarcza tu współczynnika ukończeń: nie wyliczamy go ze średniego czasu ani nie przypisujemy wzrostu komentarzom.</p>
 <details className="growth-card"><summary>Historia przeglądów</summary>{growth.reports.map(r=><p key={r.day}>Tydzień {r.day}: {names[platform]} · mediana {num(r.data.summaries[platform].medianViews)} wyświetleń · {r.data.summaries[platform].measured} publikacji z danymi</p>)}</details></>}
 {tab==='engagement'&&<><article className="growth-card"><h3>Wyszukiwanie AI · Instagram i TikTok</h3><p>UX, strony internetowe, branding, AI, CRM i automatyzacje social mediów. Posty po polsku i angielsku; komentarz w języku publikacji.</p><label><input type="checkbox" checked={growth.discoverySettings.enabled} disabled={busy} onChange={e=>save({action:'engagement-settings',enabled:e.target.checked})}/> Wyszukuj codziennie, również przy wstrzymanym publikowaniu</label><div className="actions"><button disabled={busy||['queued','running'].includes(growth.discoverySettings.status)} onClick={()=>save({action:'engagement-discover'})}>Szukaj teraz</button></div><p role="status">{({idle:'Uruchom wyszukiwanie lub włącz automat.',queued:'Wyszukiwanie w kolejce. Worker podejmie je w ciągu kilku minut.',running:'AI wyszukuje posty i przygotowuje komentarze…',done:growth.discoverySettings.result,failed:'Wyszukiwanie nie powiodło się: '+growth.discoverySettings.error})[growth.discoverySettings.status]}</p>{growth.discoverySettings.finished_at&&<small>Ostatnie zakończenie: {new Date(growth.discoverySettings.finished_at).toLocaleString('pl-PL')}</small>}<p>Do 5 propozycji komentarzy dziennie. Posty pozostają zapisane w historii.</p></article><p>Wyszukiwanie obejmuje publiczne, indeksowane posty. Zawsze otwórz oryginał i sprawdź aktualny kontekst. Zatwierdzenie zapisuje tekst w Studio; komentarz dodajesz ręcznie w aplikacji. System nie lajkuje, nie obserwuje i nie wysyła wiadomości.</p><p>{growth.discovery?new Date(growth.discovery.created_at).toLocaleString('pl-PL')+' · '+growth.discovery.message:'Pierwsze wyszukiwanie oczekuje na cykl workera.'}</p>
 <details className="growth-card"><summary>Dodaj znalezioną publikację</summary><form onSubmit={async e=>{e.preventDefault();if(await save({action:'engagement-add',url,text:source})){setUrl('');setSource('');}}}><label>Pełny link Instagram / TikTok<input type="url" required value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Treść publikacji / kontekst<textarea required minLength={20} maxLength={5000} rows={5} value={source} onChange={e=>setSource(e.target.value)}/></label><button disabled={busy}>Dodaj do przygotowania</button></form></details>
 <label className="publication-filter"><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/> Pokaż również wykonane i pominięte</label><div className="growth-columns">{items.map(item=><EngagementCard key={item.id+':'+Boolean(item.draft)} item={item} busy={busy} save={save}/>)}</div>{!items.length&&<p>Brak propozycji dla tej platformy. Możesz dodać publiczny link z treścią; wyszukiwanie nie gwarantuje dostępnych wyników każdego dnia.</p>}</>}
 </section>;
}
