'use client';
import {useState} from 'react';
import MetricCharts from './MetricCharts';
const fields=[['views','Wyświetlenia'],['likes','Polubienia'],['comments','Komentarze'],['reach','Zasięg'],['saved','Zapisania'],['shares','Udostępnienia']];
const number=n=>typeof n==='number'?n.toLocaleString('pl-PL'):'—';
export default function MetricsPanel({data,platform}){
 const [format,setFormat]=useState('all'),[sort,setSort]=useState('day');
 const rows=(data.analytics||[]).filter(p=>(platform==='all'||p.platform===platform)&&(format==='all'||p.format===format)).sort((a,b)=>sort==='day'?b.day.localeCompare(a.day):(b.metrics?.[sort]??-1)-(a.metrics?.[sort]??-1));
 return <section className="metrics-panel"><p className="eyebrow">{platform==='tiktok'?'TIKTOK':'INSTAGRAM'} / WYNIKI PUBLIKACJI</p><h2>Metryki · {platform==='tiktok'?'TikTok':'Instagram'}</h2><p>{platform==='tiktok'?'TikTok: odczyt z Buffer co godzinę; Buffer odświeża statystyki raz dziennie.':'Instagram: synchronizacja statystyk co godzinę.'} „—” oznacza brak danych z API. Wyświetlenia mogą obejmować ponowne odtworzenia; zasięg oznacza unikalne konta.</p><div className="controls"><label>Format <select aria-label="Format" value={format} onChange={e=>setFormat(e.target.value)}><option value="all">Wszystkie</option><option value="post">Posty</option><option value="reel">Rolki</option></select></label><label>Sortowanie <select aria-label="Sortowanie" value={sort} onChange={e=>setSort(e.target.value)}><option value="day">Najnowsze</option>{fields.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><section className="stats">{fields.slice(0,3).map(([key,label])=>{const known=rows.filter(p=>typeof p.metrics?.[key]==='number');return <article key={key}><small>{label}</small><strong>{known.length?number(known.reduce((sum,p)=>sum+p.metrics[key],0)):'—'}</strong><small>Dane dla {known.length} z {rows.length} publikacji</small></article>;})}</section><MetricCharts key={platform+format} rows={rows} samples={data.metricSamples}/><div className="metrics-table" role="region" aria-label="Wyniki poszczególnych publikacji" tabIndex={0}><table><thead><tr><th scope="col">Publikacja</th>{fields.map(([key,label])=><th scope="col" key={key}>{label}</th>)}<th scope="col">Aktualizacja</th></tr></thead><tbody>{rows.map(p=><tr key={p.media_id}><th scope="row"><small>{p.day} · {p.platform==='tiktok'?'TikTok':'Instagram'} · {p.format==='reel'?'Rolka':'Post'}</small><a href={p.permalink} target="_blank" rel="noreferrer">{p.topic||'Publikacja'} ↗</a></th>{fields.map(([key])=><td key={key}>{number(p.metrics?.[key])}</td>)}<td>{p.metrics?.collectedAt?new Date(p.metrics.collectedAt).toLocaleString('pl-PL'):'Oczekuje na synchronizację'}</td></tr>)}</tbody></table></div>{!rows.length&&<p>Brak opublikowanych materiałów w tym filtrze.</p>}</section>;
}
