'use client';
import {useState} from 'react';
const definitions=[['views','Wyświetlenia','#35f46a'],['likes','Polubienia','#55b7ff'],['comments','Komentarze','#c099ff']];
const interactions=[['likes','Polubienia','#35f46a'],['comments','Komentarze','#55b7ff'],['saved','Zapisania','#c099ff'],['shares','Udostępnienia','#ffba69']];
const fmt=n=>n.toLocaleString('pl-PL',{maximumFractionDigits:0});
export default function MetricCharts({rows,samples}){
 const [days,setDays]=useState(30),[metric,setMetric]=useState('views'),[selected,setSelected]=useState('all'),[hover,setHover]=useState(null);
 const effective=rows.filter(r=>selected==='all'||r.media_id===selected),ids=new Set(effective.map(r=>r.media_id));
 const buckets=new Map(),cutoff=Date.now()-days*86400000;
 for(const s of samples||[]){if(!ids.has(s.media_id)||new Date(s.bucket).getTime()<cutoff)continue;const key=s.bucket;const entry=buckets.get(key)||{time:new Date(key).getTime(),total:0,count:0};if(typeof s.metrics?.[metric]==='number'){entry.total+=s.metrics[metric];entry.count++;}buckets.set(key,entry);}
 const points=[...buckets.values()].sort((a,b)=>a.time-b.time),valid=points.filter(p=>p.count>0),max=Math.max(4,Math.ceil(Math.max(0,...valid.map(p=>p.total))/4)*4),start=points[0]?.time||0,end=points.at(-1)?.time||start;
 const x=p=>end===start?370:65+(p.time-start)/(end-start)*610,y=p=>230-p.total/max*180;
 const chosen=definitions.find(d=>d[0]===metric),segments=[];let segment=[];
 for(const p of points){if(p.count){segment.push(`${x(p)},${y(p)}`);}else if(segment.length){segments.push(segment.join(' '));segment=[];}}if(segment.length)segments.push(segment.join(' '));
 const parts=interactions.map(([key,label,color])=>({key,label,color,value:effective.reduce((n,r)=>n+(typeof r.metrics?.[key]==='number'?r.metrics[key]:0),0),known:effective.filter(r=>typeof r.metrics?.[key]==='number').length})),total=parts.reduce((n,p)=>n+p.value,0),circumference=2*Math.PI*75;let offset=0;
 const time=t=>new Date(t).toLocaleString('pl-PL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
 const active=hover===null?valid.at(-1):valid[hover];
 return <section className="chart-dashboard" aria-label="Wykresy wyników"><div className="chart-filters"><label>Historia pomiarów <select aria-label="Historia pomiarów" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 dni</option><option value={30}>30 dni</option><option value={90}>90 dni</option></select></label><label>Publikacja na wykresach <select aria-label="Publikacja na wykresach" value={selected} onChange={e=>{setSelected(e.target.value);setHover(null);}}><option value="all">Wszystkie w wybranym formacie</option>{rows.map(r=><option key={r.media_id} value={r.media_id}>{r.topic||r.day}</option>)}</select></label></div><div className="chart-panels"><article className="chart-card"><div className="chart-heading"><h3>Wyniki w czasie</h3><select aria-label="Metryka wykresu liniowego" value={metric} onChange={e=>{setMetric(e.target.value);setHover(null);}}>{definitions.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></div><p className="chart-reading">{active?<><strong style={{color:chosen[2]}}>{fmt(active.total)}</strong> <span>{time(active.time)} · dane dla {active.count} publikacji</span></>:'Oczekuje na pierwszy pomiar'}</p><svg viewBox="0 0 720 280" role="img" aria-label={`Wykres liniowy: ${chosen[1]}. ${valid.length} pomiarów. Ostatnia wartość ${active?fmt(active.total):'brak danych'}.`}>
 {[0,.25,.5,.75,1].map(n=><g key={n}><line x1="65" x2="675" y1={230-n*180} y2={230-n*180} stroke="#263c32" strokeDasharray="3 5"/><text x="53" y={235-n*180} textAnchor="end" fill="#a5bdb2" fontSize="13">{Intl.NumberFormat('pl-PL',{notation:'compact',maximumFractionDigits:0}).format(max*n)}</text></g>)}
 {segments.map((p,i)=><polyline key={i} points={p} fill="none" stroke={chosen[2]} strokeWidth="3"/>)}
 {valid.map((p,i)=><circle key={p.time} cx={x(p)} cy={y(p)} r={valid.length<3?5:3} fill={chosen[2]} tabIndex={0} onMouseEnter={()=>setHover(i)} onFocus={()=>setHover(i)} aria-label={`${time(p.time)}: ${fmt(p.total)}`}><title>{time(p.time)}: {fmt(p.total)}</title></circle>)}
 {valid.length>0&&<><text x="65" y="263" fill="#a5bdb2" fontSize="13">{time(start)}</text>{end!==start&&<text x="675" y="263" textAnchor="end" fill="#a5bdb2" fontSize="13">{time(end)}</text>}</>}
 </svg><p className="chart-note">{valid.length<2?'Linia pojawi się po drugim pomiarze. Historia jest zbierana od uruchomienia dashboardu.':'Suma liczników w chwili pomiaru, nie przyrost dzienny. Nowe publikacje mogą zwiększać sumę.'}</p></article><article className="chart-card"><h3>Struktura interakcji</h3><p className="chart-note">Ostatni dostępny pomiar · wybrane publikacje</p><div className="donut-layout"><svg viewBox="0 0 220 220" role="img" aria-label={`Wykres kołowy: ${total?parts.map(p=>p.label+' '+p.value).join(', '):'Brak zarejestrowanych interakcji'}`}><circle cx="110" cy="110" r="75" fill="none" stroke="#263c32" strokeWidth="26"/>{total>0&&parts.filter(p=>p.value>0).map(p=>{const dash=p.value/total*circumference,previous=offset;offset+=dash;return <circle key={p.key} cx="110" cy="110" r="75" fill="none" stroke={p.color} strokeWidth="26" strokeDasharray={`${dash} ${circumference-dash}`} strokeDashoffset={-previous} transform="rotate(-90 110 110)"><title>{p.label}: {fmt(p.value)} ({(p.value/total*100).toFixed(1)}%)</title></circle>;})}<text x="110" y="110" textAnchor="middle" fill="#f2f4f3" fontSize="30">{parts.some(p=>p.known)?fmt(total):'—'}</text><text x="110" y="135" textAnchor="middle" fill="#a5bdb2" fontSize="13">interakcji</text></svg><ul className="chart-legend">{parts.map(p=><li key={p.key}><span className="legend-dot" style={{background:p.color}}/><span>{p.label}<small>{p.known}/{effective.length} publikacji</small></span><strong>{p.known?fmt(p.value):'—'}</strong></li>)}</ul></div>{!total&&<p className="chart-note">Gdy pojawią się interakcje, koło pokaże ich udziały procentowe.</p>}</article></div></section>;
}
