'use client';
import ReplaceButton from './ReplaceButton';
import PublishButton from './PublishButton';
import MetricsPanel from './MetricsPanel';
import TikTokPanel from './TikTokPanel';
import {useState,useEffect} from 'react';
import ReelsPanel from './ReelsPanel';
const base='/studio-social';
const labels={regenerating:'Generowanie nowej treści','replacement-failed':'Nie udało się wygenerować zamiennika',draft:'Do akceptacji',approved:'Gotowy',uploading:'Przesyłanie',publishing:'Publikowanie',verifying:'Weryfikacja',verified:'Opublikowany','needs-attention':'Wymaga uwagi'};
export default function Page(){const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState(null),[view,setView]=useState('queue'),[publication,setPublication]=useState('pending'),[format,setFormat]=useState('posts'),[platform,setPlatform]=useState('instagram');
 async function load(){try{const r=await fetch(base+'/api',{cache:'no-store'});if(r.status===401){location.assign(base+'/login');return;}if(!r.ok)throw Error('Nie udało się pobrać panelu');setData(await r.json());}catch(e){setError(e.message);}}
 useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t);},[]);
 async function act(body){setBusy(true);setError('');try{const r=await fetch(base+'/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw Error(result.error);setEdit(null);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const imported=(data?.history||[]).map(p=>({id:'ig:'+p.media_id,day:p.published_at.slice(0,10),status:'verified',permalink:p.permalink,remoteImage:p.media_url,content:{topic:p.editorial_note||p.caption.slice(0,100)||'Post z Instagrama — brak opisu',caption:p.caption,hashtags:[],alt:p.editorial_note||'Post z Instagrama'},imported:true}));
 const posts=[...(data?.posts||[]),...imported].sort((a,b)=>b.day.localeCompare(a.day)),queue=posts.filter(p=>p.status!=='verified').sort((a,b)=>a.day.localeCompare(b.day)),live=posts.filter(p=>p.status==='verified');
 return <main><header><a href="https://mindvortex.pro/en" className="brand">MIND VORTEX<span>SOCIAL STUDIO</span></a><button onClick={async()=>{await fetch(base+'/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});location.assign(base+'/login');}}>Wyloguj</button><span className="account">@mindvortex.pro · EN</span></header><section className="intro"><p className="eyebrow">CONTENT / DESIGN / CONSISTENCY</p><h1>Codziennie.<br/><em>W głosie studia.</em></h1><p>Kalendarz, treści i publikacje w jednym miejscu.</p></section>
 {error&&<div role="alert" className="error">{error}</div>}
 {!data?<p role="status">Ładowanie panelu…</p>:<><nav className="platform-tabs" aria-label="Platforma publikacji">{[['instagram','Instagram'],['tiktok','TikTok']].map(([key,label])=><button key={key} className={platform===key?'selected':''} aria-pressed={platform===key} onClick={()=>{setPlatform(key);setFormat(current=>current==='metrics'?'metrics':key==='tiktok'?'reels':'posts');}}>{label}</button>)}</nav><nav className="format-tabs" aria-label="Format treści"><button className={format==='posts'?'selected':''} aria-pressed={format==='posts'} onClick={()=>setFormat('posts')}>Posty</button><button className={format==='reels'?'selected':''} aria-pressed={format==='reels'} onClick={()=>setFormat('reels')}>Rolki</button><button className={format==='metrics'?'selected':''} aria-pressed={format==='metrics'} onClick={()=>setFormat('metrics')}>Metryki</button></nav>{format!=='metrics'&&<label className="publication-filter">Status publikacji <select value={publication} onChange={e=>{setPublication(e.target.value);setView(e.target.value==='pending'?'queue':e.target.value==='published'?'history':'feed');}}><option value="all">Wszystkie</option><option value="pending">Nieopublikowane</option><option value="published">Opublikowane</option></select></label>}{format==='posts'&&platform==='instagram'?<><section className="stats"><article><small>Publikowanie</small><strong>{data.settings.paused?'Wstrzymane':'Aktywne'}</strong></article><article><small>Gotowe w kolejce</small><strong>{queue.filter(p=>p.status==='approved').length}</strong></article><article><small>Potwierdzone publikacje</small><strong>{live.length}</strong></article><article><small>Godzina · Warszawa</small><strong>{String(data.settings.hour).padStart(2,'0')}:00</strong></article></section>
 <section className="controls"><button disabled={busy} onClick={()=>act({action:'settings',...data.settings,paused:!data.settings.paused})}>{data.settings.paused?'Wznów publikowanie':'Wstrzymaj publikowanie'}</button><label>Nowe posty <select disabled={busy} value={String(data.settings.autopilot)} onChange={e=>act({action:'settings',...data.settings,autopilot:e.target.value==='true'})}><option value="false">Do zatwierdzenia</option><option value="true">Automatycznie gotowe</option></select></label><label>Godzina <select disabled={busy} value={data.settings.hour} onChange={e=>act({action:'settings',...data.settings,hour:Number(e.target.value)})}>{Array.from({length:24},(_,i)=><option key={i} value={i}>{String(i).padStart(2,'0')}:00</option>)}</select></label></section>
 <nav><button className={view==='queue'?'selected':''} onClick={()=>{setView('queue');setPublication('pending');}}>Kolejka / {queue.length}</button><button className={view==='feed'?'selected':''} onClick={()=>{setView('feed');setPublication('all');}}>Podgląd feedu</button><button className={view==='history'?'selected':''} onClick={()=>{setView('history');setPublication('published');}}>Historia i wyniki</button></nav>
 <div className="toolbar"><button disabled={busy} onClick={()=>act({action:'sync'})}>Synchronizuj Instagram</button><h2>{view==='queue'?'Następne publikacje':view==='feed'?'Najnowsze u góry':'Opublikowane i zweryfikowane'}</h2>{view==='queue'&&<div><button disabled={busy} onClick={()=>act({action:'generate'})}>{busy?'Pracuję…':'Przygotuj 7 dni'}</button><button disabled={busy||!queue.some(p=>p.status==='draft')} onClick={()=>act({action:'approve-all'})}>Zatwierdź kolejkę</button></div>}</div>
 <section className={'grid '+(view==='feed'?'feed':'')}>{(view==='queue'?queue:view==='history'?live:posts).map(p=><article className="card" key={p.id}><img src={p.remoteImage||base+'/media/'+p.image} alt={p.content.alt}/><div className="cardbody"><div className="meta"><time>{p.day}</time><span>{p.imported?'Zaimportowany z Instagrama':labels[p.status]||p.status}</span></div><h3>{p.content.topic}</h3>{view!=='feed'&&<><p className="caption">{p.content.caption}</p><p className="tags">{p.content.hashtags.join(' ')}</p>{p.error&&<p className="error">{p.error}</p>}{p.metrics&&<p>Zasięg: {p.metrics.reach??'—'} · Zapisania: {p.metrics.saved??'—'} · Polubienia: {p.metrics.likes??'—'}</p>}<div className="actions"><ReplaceButton item={p} target="post" busy={busy} act={act}/><PublishButton item={p} target="post" busy={busy} act={act} paused={data.settings.paused}/>{['draft','approved'].includes(p.status)&&<><button disabled={busy} onClick={()=>setEdit(structuredClone(p))}>Edytuj</button><button disabled={busy} onClick={()=>act({action:p.status==='draft'?'approve':'draft',id:p.id})}>{p.status==='draft'?'Zatwierdź':'Cofnij do szkicu'}</button></>}{p.status==='needs-attention'&&<button disabled={busy} onClick={()=>act({action:'reconcile',id:p.id})}>Sprawdź na Instagramie</button>}{p.permalink&&<a href={p.permalink} target="_blank" rel="noreferrer">Otwórz post ↗</a>}</div></>}</div></article>)}</section>
 {!(view==='queue'?queue:view==='history'?live:posts).length&&<div className="empty">{view==='history'?'Historia pojawi się po pierwszej potwierdzonej publikacji.':'Przygotuj siedem dni treści, aby wypełnić kalendarz.'}</div>}
 </>:format==='metrics'?<MetricsPanel key={platform} data={data} platform={platform}/>:platform==='tiktok'?<TikTokPanel busy={busy} act={act} data={data} format={format} publication={publication}/>:<ReelsPanel data={data} busy={busy} act={act} publication={publication}/>}
 <details><summary>Dziennik pracy</summary>{data.events.map((e,i)=><p key={i}>{new Date(e.created_at).toLocaleString('pl-PL')} — {e.message}</p>)}</details></>}
 {edit&&<div className="overlay"><section role="dialog" aria-modal="true" aria-label="Edycja posta" className="editor"><h2>Edytuj post · {edit.day}</h2><p>Zapis zmian przywraca status „Do akceptacji”.</p>{['topic','headline','caption','alt'].map(key=><label key={key}>{({topic:'Temat',headline:'Nagłówek grafiki',caption:'Opis',alt:'Tekst alternatywny'})[key]}<textarea rows={key==='caption'?7:2} value={edit.content[key]} onChange={e=>setEdit({...edit,content:{...edit.content,[key]:e.target.value}})}/></label>)}<label>Punkty grafiki (jeden na linię)<textarea value={edit.content.points.join('\n')} onChange={e=>setEdit({...edit,content:{...edit.content,points:e.target.value.split('\n')}})}/></label><label>Hashtagi<input value={edit.content.hashtags.join(' ')} onChange={e=>setEdit({...edit,content:{...edit.content,hashtags:e.target.value.split(/\s+/)}})}/></label>{error&&<p role="alert" className="error">{error}</p>}<div className="actions"><button disabled={busy} onClick={()=>act({action:'save',id:edit.id,content:edit.content})}>Zapisz</button><button disabled={busy} onClick={()=>setEdit(null)}>Anuluj</button></div></section></div>}
 <footer>Mind Vortex · Treści po angielsku · Europe/Warsaw</footer></main>;
}
