'use client';
import ReplaceButton from './ReplaceButton';
import PublishButton from './PublishButton';
export default function ReelsPanel({data,busy,act,publication}){
 const cfg=data.reelSettings,rows=[...(data.reels||[])].sort((a,b)=>Number(a.status==='verified')-Number(b.status==='verified')||a.day.localeCompare(b.day));if(!cfg)return null;
 const pending=rows.filter(r=>r.status!=='verified'),ready=pending.filter(r=>r.status==='approved');
 const visible=rows.filter(r=>publication==='all'||(r.status==='verified')===(publication==='published'));
 const labels={regenerating:'Generowanie nowej treści','replacement-failed':'Nie udało się wygenerować zamiennika',approved:'Gotowa',uploading:'Przetwarzanie w Instagramie',publishing:'Publikowanie',verifying:'Weryfikacja',verified:'Opublikowana','needs-attention':'Wymaga uwagi'};
 return <section className="reels-panel" aria-labelledby="reels-heading"><div className="toolbar"><div><p className="eyebrow">REELS / 3 TYGODNIE DO PRZODU</p><h2 id="reels-heading">Rolki · co 2 dni</h2><p>{cfg.interval_days?'Co '+cfg.interval_days+' dni':['Niedziela','Poniedziałek','Wtorek','Środa','Czwartek','Piątek','Sobota'][cfg.weekday]} · {String(cfg.hour).padStart(2,'0')}:00 · Warszawa. Gotowe: {ready.length}/{cfg.horizon}.</p><p>{data.settings.paused?'Publikacje wstrzymane globalnie.':cfg.enabled?'Automatyczne przygotowanie i publikacja aktywne.':'Automatyzacja rolek wstrzymana.'}</p></div><button disabled={busy} onClick={()=>act({action:'reel-settings',enabled:!cfg.enabled})}>{cfg.enabled?'Wstrzymaj rolki':'Wznów rolki'}</button></div><div className="grid">{visible.map(r=><article className="card" key={r.id}><video controls playsInline preload="metadata" poster={'/studio-social/media/'+r.video.replace(/\.mp4$/,'.jpg')} aria-label={r.content.topic} src={'/studio-social/media/'+r.video}/><div className="cardbody"><div className="meta"><time>{r.day}{r.status==='verified'?'':' · '+String(cfg.hour).padStart(2,'0')+':00'}</time><span>{labels[r.status]||r.status}</span></div><h3>{r.content.topic}</h3><p className="caption">{r.content.caption}</p><p className="tags">{r.content.hashtags.join(' ')}</p>{r.error&&<p className="error">{r.error}</p>}{r.content.source&&<a href={r.content.source.url} target="_blank" rel="noreferrer">Źródło informacji ↗</a>}<div className="actions"><ReplaceButton item={r} target="reel" busy={busy} act={act}/><PublishButton item={r} target="reel" busy={busy} act={act} paused={data.settings.paused||!cfg.enabled}/>{r.status==='needs-attention'&&<button disabled={busy} onClick={()=>act({action:'reel-reconcile',id:r.id})}>Sprawdź publikację</button>}{r.permalink&&<a href={r.permalink} target="_blank" rel="noreferrer">Otwórz rolkę ↗</a>}</div></div></article>)}</div>{!visible.length&&<p>Brak rolek dla wybranego statusu.</p>}</section>;
}
