'use client';
import ReplaceButton from './ReplaceButton';
import PublishButton from './PublishButton';
import {useState} from 'react';
function CarouselPreview({assets,topic}){const [slide,setSlide]=useState(0);return <div className="swipe-preview"><img src={'/studio-social/media/'+assets[slide]} alt={'Slajd '+(slide+1)+': '+topic}/><div className="swipe-controls"><button aria-label="Poprzedni slajd" disabled={slide===0} onClick={()=>setSlide(slide-1)}>←</button><span>Slajd {slide+1} z {assets.length}</span><button aria-label="Następny slajd" disabled={slide===assets.length-1} onClick={()=>setSlide(slide+1)}>→</button></div></div>;}
export default function TikTokPanel({data,format,publication,busy,act}){
 const own=data.tiktokJobs||[],mirrors=(data.reels||[]).filter(r=>!own.some(j=>j.reel_id===r.id)).map(r=>({...r,assets:[r.video],status:r.status==='verified'?'awaiting-mirror':r.status==='approved'?'ready':r.status,shared:true,permalink:null}));
 const rows=[...own,...mirrors].filter(r=>format==='posts'?r.kind==='carousel':r.kind!=='carousel').filter(r=>publication==='all'||(r.status==='published')===(publication==='published')).sort((a,b)=>Number(a.status==='published')-Number(b.status==='published')||a.day.localeCompare(b.day)),labels={regenerating:'Generowanie nowej treści','replacement-failed':'Nie udało się wygenerować zamiennika',ready:'Gotowy',published:'Opublikowany',submitted:'Przekazany do Buffer',submitting:'Przesyłanie','needs-attention':'Wymaga uwagi','awaiting-mirror':'Oczekuje na synchronizację'};
 return <section className="reels-panel"><p className="eyebrow">TIKTOK / @MINDVORTEX.PRO</p><h2>{format==='posts'?'Karuzele · trzy powiązane posty':'Rolka codziennie'}</h2><p>{format==='posts'?'Co 2 dni, dzień po rolce na Instagramie · 18:00 · Warszawa. Trzy tematycznie powiązane posty w jednej karuzeli.':'Codziennie · 18:00 · Warszawa. Te same rolki co na Instagramie oraz dodatkowe materiały pomiędzy nimi.'}</p><p>{data.tiktokConnected?(data.settings.paused||!data.reelSettings.enabled?'Publikowanie wstrzymane.':'Buffer połączony. Publikowanie z serwera aktywne.'):'Oczekuje na połączenie z Buffer.'}</p><p>Materiały czekają w tym panelu i trafiają do Buffer w dniu publikacji.</p><a href="https://publish.buffer.com/channels/6aa44144cd8b9c702c4f2f4c/schedule" target="_blank" rel="noreferrer">Otwórz kanał w Buffer ↗</a><div className="grid" style={{marginTop:24}}>{rows.map(r=><article className="card" key={r.id}>{r.kind==='carousel'?<CarouselPreview assets={r.assets} topic={r.content.topic}/>:<video controls playsInline preload="metadata" poster={'/studio-social/media/'+r.assets[0].replace(/\.mp4$/,'.jpg')} src={'/studio-social/media/'+r.assets[0]} aria-label={r.content.topic}/>}<div className="cardbody"><div className="meta"><time>{r.day} · 18:00</time><span>{labels[r.status]||r.status}</span></div><h3>{r.content.topic}</h3><p>{r.kind==='carousel'?'Karuzela · 3 zdjęcia':r.shared||(r.reel_id&&!r.content.independentTikTok)?'Rolka · Instagram + TikTok':'Rolka · TikTok'}</p><p className="caption">{r.content.caption}</p><p className="tags">{r.content.hashtags.join(' ')}</p>{<ReplaceButton item={r} target={r.shared?"tiktok-reel":"tiktok"} busy={busy} act={act}/>} {<PublishButton item={r} target={r.shared?"tiktok-reel":"tiktok"} busy={busy} act={act} paused={data.settings.paused||!data.reelSettings.enabled}/>} {r.error&&<p className="error">{r.error}</p>}{r.permalink&&<a href={r.permalink} target="_blank" rel="noreferrer">Otwórz publikację ↗</a>}</div></article>)}</div>{!rows.length&&<p className="empty">Brak treści dla wybranego statusu.</p>}</section>;
}
